### Create paper

POST {{host}}/papers
Content-Type: application/json

< input/paper_create.json


### Get papers

GET {{host}}/papers
Content-Type: application/json

### Get paper

GET {{host}}/papers/4
Content-Type: application/json

### Update paper

PUT {{host}}/papers/4
Content-Type: application/json

< input/paper_update.json

### Delete paper

DELETE {{host}}/papers/4
Content-Type: application/json
