server:
  port: ${port:8080}

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver


---

spring:
  config:
    activate:
      on-profile: heroku
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5

